apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-config
data:
{{ (.Files.Glob "*.db").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-zone-config
data:
{{ (.Files.Glob "*.conf").AsConfig | nindent 2 }}
