apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns-cheetahfox.fullname" . }}
  labels:
    {{- include "dns-cheetahfox.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}  
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "dns-cheetahfox.selectorLabels" . | nindent 4 }}
